// This file was auto-generated by ML.NET Model Builder.

namespace CVMatchPro
{
    using Microsoft.ML;
    using Microsoft.ML.Data;
    using System;
    using System.Linq;
    using System.IO;
    using System.Collections.Generic;
    public partial class MLModel
    {
        /// <summary>
        /// model input class for MLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Competences")]
            public string Competences { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Experience")]
            public string Experience { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Formation")]
            public string Formation { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Competences")]
            public float[] Competences { get; set; }

            [ColumnName(@"Experience")]
            public float[] Experience { get; set; }

            [ColumnName(@"Formation")]
            public float[] Formation { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
